name: gps_gaussian
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch=2.0.0
  - torchvision=0.15.0
  - torchaudio=2.0.0
  - pytorch-cuda=11.8
  - tqdm
  - tensorboard
  - scipy
  - numpy<2
  - pip:
    - opencv-python
    - taichi==1.5.0
    - yacs==0.1.8
